### ISSUE TITLE
m68k-amigaos-objdump crashes

### ISSUE THREAD

**Issue by alexalkis** [bebbo/amiga-gcc#314]
It crashes for at least the last two commits.
m68k-amigaos-objdump -D dl

[dl.zip](https://github.com/bebbo/amiga-gcc/files/10061045/dl.zip)
```
Program received signal SIGSEGV, Segmentation fault.
0x000055555558e882 in find_closest_symbol_index ()
(gdb) bt
#0  0x000055555558e882 in find_closest_symbol_index ()
#1  0x0000555555595366 in disassemble_section ()
#2  0x00005555555d1966 in bfd_map_over_sections ()
#3  0x000055555558f11f in disassemble_data ()
#4  0x00005555555925ba in dump_bfd ()
#5  0x0000555555592855 in display_any_bfd ()
#6  0x0000555555592934 in display_file ()
#7  0x000055555558e63e in main ()
```

**Comment by bebbo** [comment]
you've been hit by an uninitialized variable for 12332468 damage...

**Comment by alexalkis** [comment]
Fixed.  Thanks!
